'use client';

import { useEffect, useRef } from 'react';

/**
 * DynamicFavicon component
 * Changes the favicon every 2 seconds in a loop between two Next.js generated icons
 * This creates an animated effect in the browser tab
 * 
 * Icons are generated using Next.js ImageResponse API:
 * - /favicon.ico is generated by app/icon.js (purple background with white "B")
 * - /api/favicon2 is generated by app/api/favicon2/route.js (black background with purple "B")
 */
export default function DynamicFavicon() {
  // Use ref to persist state across renders
  const currentIndexRef = useRef(0);
  const intervalRef = useRef(null);
  const isInitializedRef = useRef(false);
  
  useEffect(() => {
    // Array of favicon paths to cycle through
    // Using Next.js generated icons:
    // - /favicon.ico is generated by app/icon.js (purple background with white "B")
    // - /api/favicon2 is generated by app/api/favicon2/route.js (black background with purple "B")
    const favicons = ['/favicon.ico', '/api/favicon2'];
    
    /**
     * Updates the favicon in the document head
     * Works with Next.js metadata by updating/consolidating favicon links
     * @param {string} faviconPath - Path to the favicon file
     */
    const updateFavicon = (faviconPath) => {
      try {
        // Ensure DOM is ready
        if (typeof document === 'undefined' || !document.head) {
          return;
        }
        
        const head = document.head;
        
        // Create cache-busted URL to force browser reload
        const timestamp = Date.now();
        const faviconUrl = `${faviconPath}?v=${timestamp}`;
        
        // Find all favicon links (Next.js metadata might create multiple)
        const allFaviconLinks = head.querySelectorAll(
          "link[rel='icon'], link[rel='shortcut icon']"
        );
        
        // Update existing favicon links if they exist, otherwise create new ones
        let foundIcon = false;
        let foundShortcut = false;
        
        allFaviconLinks.forEach((link) => {
          const rel = link.getAttribute('rel');
          if (rel === 'icon') {
            link.href = faviconUrl;
            link.type = 'image/png'; // Next.js generates PNG icons
            foundIcon = true;
          } else if (rel === 'shortcut icon') {
            link.href = faviconUrl;
            link.type = 'image/png';
            foundShortcut = true;
          }
        });
        
        // Create new links if they don't exist
        if (!foundIcon) {
          const iconLink = document.createElement('link');
          iconLink.rel = 'icon';
          iconLink.type = 'image/png';
          iconLink.href = faviconUrl;
          head.appendChild(iconLink);
        }
        
        if (!foundShortcut) {
          const shortcutLink = document.createElement('link');
          shortcutLink.rel = 'shortcut icon';
          shortcutLink.type = 'image/png';
          shortcutLink.href = faviconUrl;
          head.appendChild(shortcutLink);
        }
        
        // Force browser update by triggering a reflow
        void head.offsetHeight;
      } catch (error) {
        console.error('Error updating favicon:', error);
      }
    };
    
    /**
     * Switches to the next favicon in the array
     * This function is called by the interval
     */
    const switchFavicon = () => {
      try {
        // Increment index and wrap around using modulo
        // This ensures we cycle: 0 -> 1 -> 0 -> 1 -> ...
        const newIndex = (currentIndexRef.current + 1) % favicons.length;
        currentIndexRef.current = newIndex;
        
        // Update favicon with the new path
        updateFavicon(favicons[newIndex]);
      } catch (error) {
        console.error('Error switching favicon:', error);
      }
    };
    
    // Initialize favicon system
    const initFavicon = () => {
      // Prevent multiple initializations
      if (isInitializedRef.current) return;
      
      // Initialize immediately - Next.js metadata favicon is already set
      // We'll update it to start our dynamic cycle
      currentIndexRef.current = 0;
      isInitializedRef.current = true;
      
      // Update to initial favicon immediately (favicon.ico)
      // This ensures it's visible right away
      updateFavicon(favicons[0]);
      
      // Start interval to switch favicons every 2 seconds
      // First switch will happen after 2 seconds (to favicon2.ico)
      // Second switch will happen after another 2 seconds (back to favicon.ico)
      // And so on...
      intervalRef.current = setInterval(() => {
        switchFavicon();
      }, 2000);
    };
    
    // Initialize immediately when component mounts
    // useEffect runs after render, so DOM and Next.js metadata are ready
    let initDelay = null;
    
    if (typeof window !== 'undefined' && document.head) {
      // Small delay to ensure Next.js has applied metadata
      // But make it very short so favicon shows immediately
      initDelay = setTimeout(initFavicon, 100);
    }
    
    // Cleanup on unmount
    return () => {
      if (initDelay) {
        clearTimeout(initDelay);
      }
      if (intervalRef.current) {
        clearInterval(intervalRef.current);
        intervalRef.current = null;
      }
      isInitializedRef.current = false;
    };
  }, []);

  return null;
}
